/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.model.Users;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Stalker
 */
public class Home extends javax.swing.JFrame{
    /**
     * Creates new form Home
     */
    Users user1 = new Users();
    public Home() {
        initComponents();
        userLogged.setText(user1.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        systemLabel = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        managePanel = new javax.swing.JPanel();
        manage = new javax.swing.JLabel();
        monthlyReadingsPanel = new javax.swing.JPanel();
        monthlyReadings = new javax.swing.JLabel();
        addConsumerPanel = new javax.swing.JPanel();
        addConsumer = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        payment = new javax.swing.JLabel();
        headBarPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        bottomBarPanel = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();
        userLogo = new javax.swing.JLabel();
        userLogged = new javax.swing.JLabel();
        addAdminEmployeeLabel = new javax.swing.JLabel();
        homeSeparator = new javax.swing.JSeparator();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Electric Billing System");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        systemLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        systemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        systemLabel.setText("Electric Billing System");

        managePanel.setToolTipText("Click to manage data");
        managePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        manage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/home/icons8_Database_Administrator_100px.png"))); // NOI18N
        manage.setText("Manage");
        manage.setToolTipText("Click to manage data");
        manage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        manage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout managePanelLayout = new javax.swing.GroupLayout(managePanel);
        managePanel.setLayout(managePanelLayout);
        managePanelLayout.setHorizontalGroup(
            managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        managePanelLayout.setVerticalGroup(
            managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manage, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        monthlyReadingsPanel.setToolTipText("Cilck to add new admin/employee");
        monthlyReadingsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        monthlyReadings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        monthlyReadings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthlyReadings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/home/icons8_Energy_Meter_100px_1.png"))); // NOI18N
        monthlyReadings.setText("Monthly Readings");
        monthlyReadings.setToolTipText("Update consumer monthly consumption");
        monthlyReadings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        monthlyReadings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout monthlyReadingsPanelLayout = new javax.swing.GroupLayout(monthlyReadingsPanel);
        monthlyReadingsPanel.setLayout(monthlyReadingsPanelLayout);
        monthlyReadingsPanelLayout.setHorizontalGroup(
            monthlyReadingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthlyReadingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monthlyReadings, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        monthlyReadingsPanelLayout.setVerticalGroup(
            monthlyReadingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthlyReadingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monthlyReadings, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        addConsumerPanel.setToolTipText("Click to add new consumer");
        addConsumerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        addConsumer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addConsumer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addConsumer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/home/icons8_Add_User_Male_100px.png"))); // NOI18N
        addConsumer.setText("Add Consumer");
        addConsumer.setToolTipText("Click to add new consumer");
        addConsumer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addConsumer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addConsumer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addConsumer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addConsumerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addConsumerPanelLayout = new javax.swing.GroupLayout(addConsumerPanel);
        addConsumerPanel.setLayout(addConsumerPanelLayout);
        addConsumerPanelLayout.setHorizontalGroup(
            addConsumerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addConsumerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addConsumer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addConsumerPanelLayout.setVerticalGroup(
            addConsumerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addConsumerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addConsumer, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        paymentPanel.setToolTipText("Click to transact bill");
        paymentPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        payment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/home/icons8_Receive_Cash_100px.png"))); // NOI18N
        payment.setText("Payment");
        payment.setToolTipText("Click to transact bill");
        payment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        payment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payment, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addConsumerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(managePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(monthlyReadingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addConsumerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthlyReadingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        headBarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/home/icons8_Delete_30px_1.png"))); // NOI18N
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/home/icons8_Expand_Arrow_30px.png"))); // NOI18N
        minimizeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headBarPanelLayout = new javax.swing.GroupLayout(headBarPanel);
        headBarPanel.setLayout(headBarPanelLayout);
        headBarPanelLayout.setHorizontalGroup(
            headBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headBarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLabel))
        );
        headBarPanelLayout.setVerticalGroup(
            headBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headBarPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(headBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeLabel)
                    .addComponent(exitLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        logoutLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/home/icons8_Logout_Rounded_Up_30px_1.png"))); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });

        userLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/home/icons8_User_30px.png"))); // NOI18N
        userLogo.setLabelFor(userLogo);
        userLogo.setToolTipText("View your profile");

        userLogged.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userLogged.setLabelFor(userLogo);
        userLogged.setText("ed");
        userLogged.setToolTipText("View your profile");

        addAdminEmployeeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addAdminEmployeeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/home/icons8_Admin_Settings_Male_30px.png"))); // NOI18N
        addAdminEmployeeLabel.setText("  Add New Admin/Employee");
        addAdminEmployeeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAdminEmployeeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAdminEmployeeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bottomBarPanelLayout = new javax.swing.GroupLayout(bottomBarPanel);
        bottomBarPanel.setLayout(bottomBarPanelLayout);
        bottomBarPanelLayout.setHorizontalGroup(
            bottomBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(userLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLogged, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(addAdminEmployeeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bottomBarPanelLayout.setVerticalGroup(
            bottomBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(userLogged, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userLogo))
            .addGroup(bottomBarPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(addAdminEmployeeLabel)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(systemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeSeparator)
                            .addComponent(headBarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bottomBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(systemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(homeSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottomBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
          logoutLabel.setForeground(Color.RED);
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        logoutLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_logoutLabelMouseExited

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        new Login().exit();
    }//GEN-LAST:event_exitLabelMouseClicked

    private void addConsumerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addConsumerMouseClicked
        this.dispose();
        new AddConsumer().setVisible(true);
    }//GEN-LAST:event_addConsumerMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void addAdminEmployeeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAdminEmployeeLabelMouseClicked
        this.dispose();
        new AddAdminEmployee().setVisible(true);
    }//GEN-LAST:event_addAdminEmployeeLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }
    void goToHome(JFrame frame){
        frame.dispose();
        new Home().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel addAdminEmployeeLabel;
    private javax.swing.JLabel addConsumer;
    private javax.swing.JPanel addConsumerPanel;
    private javax.swing.JPanel bottomBarPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel headBarPanel;
    private javax.swing.JSeparator homeSeparator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel manage;
    private javax.swing.JPanel managePanel;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel monthlyReadings;
    private javax.swing.JPanel monthlyReadingsPanel;
    private javax.swing.JLabel payment;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel systemLabel;
    private javax.swing.JLabel userLogged;
    private javax.swing.JLabel userLogo;
    // End of variables declaration//GEN-END:variables
}
